name: test

on: [workflow_dispatch]

jobs:
  clone-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Clone target repository
      run: git clone https://github.com/GaryNaramogura/test.git ./target-repo

    - name: goset
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: goset
      run: |
        cd ./target-repo
        go mod download

    - name: Run Go application
      run: |
        cd ./target-repo
        go run index.go https://chatgpt.com/ 10000 21600